### ISSUE TITLE
Can you put the LITS data into some other repository?

### ISSUE THREAD

**Issue by pongopal** [JunMa11/SegWithDistMap#10]
I can not be able to download the LITS in h5 format dataset from pan Baidu. Do you have any other repository that is easier to download from?

**Comment by JunMa11** [comment]
Hi @pongopal ,

Sorry for my late reply.

Have you got the data?

In China mainland, there are network problems when uploading big files to google drive and dropbox. Do you have any suggestions about the free network disk that I can share the h5 data?

BTW, Merry Christmas and Happy New Year:)

Best,
Jun
