### ISSUE TITLE
How to generate H5 files?

### ISSUE THREAD

**Issue by GuobinZhangTJU** [JunMa11/SegWithDistMap#11]
Hi, many thanks for your sharing.
Can you share the code for generating H5 files?
many thanks~

**Comment by GuobinZhangTJU** [comment]
the data in LiTs is also generated by: https://github.com/yulequan/UA-MT/blob/master/code/dataloaders/la_heart_processing.py? 
I found the code in the link above is used to process mri data in LA_dataset~
Thanks a lot~

**Comment by GuobinZhangTJU** [comment]
![image](https://user-images.githubusercontent.com/42600942/103351427-293d2400-4ade-11eb-96b5-2505fbd3d00a.png)

I read the .h5 file you provided on Baiduyun and made a visualization, I tried to use the preprocessing code in https://github.com/yulequan/UA-MT/blob/master/code/dataloaders/la_heart_processing.py, but it can not generate the data as you provided, can you tell me how to generate this kind of data ???  Thanks a lot~

**Comment by JunMa11** [comment]
Hi @GuobinZhangTJU 

The LiTS h5 data was generated by modifying the `la_heart_processing.py`.

Step 1: Do preprocessing and save the results as `np` files (e.g., `npz`) 
> Unfortunately, I can not find the original code, but it is very simple: resampling, applying the liver mask, and doing intensity cutoff [-160, 240] and normalization

Step 2: Converting the `np` files to `h5` files

```python
def np2h5(img_prefix )    
    train_npy = np.load(join(path, img_prefix+'.npz'))['data']
    image = np.load(path to numpy format image)
    label = np.load(path to numpy format ground truth)
    
    f = h5py.File(join(save_path, img_prefix+'.h5'), 'w')
    f.create_dataset('image', data=image, compression="gzip")
    f.create_dataset('label', data=label, compression="gzip")
    f.close()
```

**Comment by GuobinZhangTJU** [comment]
> Hi @GuobinZhangTJU
> 
> The LiTS h5 data was generated by modifying the `la_heart_processing.py`.
> 
> Step 1: Do preprocessing and save the results as `np` files (e.g., `npz`)
> 
> > Unfortunately, I can not find the original code, but it is very simple: resampling, applying the liver mask, and doing intensity cutoff [-160, 240] and normalization
> 
> Step 2: Converting the `np` files to `h5` files
> 
> ```python
> def np2h5(img_prefix )    
>     train_npy = np.load(join(path, img_prefix+'.npz'))['data']
>     image = np.load(path to numpy format image)
>     label = np.load(path to numpy format ground truth)
>     
>     f = h5py.File(join(save_path, img_prefix+'.h5'), 'w')
>     f.create_dataset('image', data=image, compression="gzip")
>     f.create_dataset('label', data=label, compression="gzip")
>     f.close()
> ```

Hi, teacher Ma, thanks a lot for your reply, here is the modified code according to the above link,

output_size = [96, 128, 160]###  which is defined according to your patch size in your published paper~
```

def covert_h5():
    listt = glob('/data2/000_test_data/images/Patient_*.nii.gz')
    for item in tqdm(listt):
        image = sitk.ReadImage(item)
        a = item.replace('images', 'labels')
        label = sitk.ReadImage(item.replace('images', 'labels'))
        image = sitk.GetArrayFromImage(image)
        label = sitk.GetArrayFromImage(label)
        label = (label == 1).astype(np.uint8)
        w, h, d = label.shape

        tempL = np.nonzero(label)
        minx, maxx = np.min(tempL[0]), np.max(tempL[0])
        miny, maxy = np.min(tempL[1]), np.max(tempL[1])
        minz, maxz = np.min(tempL[2]), np.max(tempL[2])

        px = max(output_size[0] - (maxx - minx), 0) // 2
        py = max(output_size[1] - (maxy - miny), 0) // 2
        pz = max(output_size[2] - (maxz - minz), 0) // 2
        minx = max(minx - np.random.randint(10, 20) - px, 0)
        maxx = min(maxx + np.random.randint(10, 20) + px, w)
        miny = max(miny - np.random.randint(10, 20) - py, 0)
        maxy = min(maxy + np.random.randint(10, 20) + py, h)
        minz = max(minz - np.random.randint(5, 10) - pz, 0)
        maxz = min(maxz + np.random.randint(5, 10) + pz, d)

        image = image[minx:maxx, miny:maxy, minz:maxz]  
        label = label[minx:maxx, miny:maxy, minz:maxz]

        max_hu = 240
        min_hu = -160
        image[np.where(image > max_hu)] = max_hu
        image[np.where(image < min_hu)] = min_hu

        image = (image - np.mean(image)) / np.std(image)   ##  HERE 1 *************************************************  
        image = image.astype(np.float32)
        image[label != 1] = 0  ##  HERE 2 *************************************************  
        print(label.shape)

        item = item.split("/")[-1].split(".")[0]
        f = h5py.File('/data2/000_test_data/h5/{}.h5'.format(item), 'w')
        f.create_dataset('image', data=image, compression="gzip")
        f.create_dataset('label', data=label, compression="gzip")
        f.close()

```
Please see the code in ## HERE ************************************************* above

----The normalization can be operated by the code in HERE 1?

----In HERE 2, your provided data, the intensities which except for the liver area are a same value -1.527, can I replaced by 0?



Thanks a lot~ waiting for your reply~~

**Comment by JunMa11** [comment]
Hi @JunMa11 
----The normalization can be operated by the code in HERE 1?

> Yes!

- can I replace by 0?
> Sure, but please make sure that you replace the values in both the training and testing set.

**Comment by GuobinZhangTJU** [comment]
> Hi @JunMa11
> ----The normalization can be operated by the code in HERE 1?
> 
> > Yes!
> 
> * can I replace by 0?
> 
> > Sure, but please make sure that you replace the values in both the training and testing set.

OK, got it ~ many thanks, and Happy New Year~~

**Comment by zz10001** [comment]
Hi, @JunMa11

Thanks for your great work, I met the same problem in data preprocessing, you just do follow step like this？
``1. resampling to (1,1,1) ?`` 
``2. applying the liver mask ``
``3. doing intensity cutoff [-160, 240] and normalization``
and I download from bd, then I visual it to png, some case seems to match on image and label like 48, but in 130, it seems mismatch on image and label, is it normal?
![image](https://user-images.githubusercontent.com/39954774/103509087-49356480-4e9d-11eb-9025-9ac655e46ff4.png)
![image](https://user-images.githubusercontent.com/39954774/103509083-46d30a80-4e9d-11eb-959b-f721bb29c218.png)

**Comment by JunMa11** [comment]
Hi @zz10001 ,

Sorry for my late reply. 

The data were resampled to the **median spacing** rather than (1,1,1).

The image and label should be matched. However, all the data have been preprocessed, so the appearances may not common.

Best,
Jun

**Comment by zz10001** [comment]
Thanks for your kind help, I get it!

**Comment by zz10001** [comment]
Sorry to bother you again,
       Is the **median spacing** in the folder containing all ct file, for example, it has 8 files in ct fold, I use target(list) to store all spacing, Then I call the function in numpy to count the median value of each dimension spacing like this 
``target_spacing_percentile = 50``  
``target = np.percentile(np.vstack(spacings), target_spacing_percentile, 0)``, 
Finally i get the target spacing in log.txt, Is my understanding correct？ Here is my log.txt
[log.txt](https://github.com/JunMa11/SegWithDistMap/files/5781620/log.txt)

**Comment by JunMa11** [comment]
Hi @zz10001 ,

Any questions are welcome.

> Is the median spacing in the folder containing all ct file

Yes! You can do the resampling and intensity normalization with nnUNet (if you are familiar with it).

**Comment by zz10001** [comment]
> Yes! You can do the resampling and intensity normalization with nnUNet (if you are familiar with it).

Thanks! I will learn the data process on nnUnet
