### ISSUE TITLE
A questions about the AAAI SDF implementation.

### ISSUE THREAD

**Issue by tommy-qichang** [JunMa11/SegWithDistMap#12]
Hi there,

Thank you so much for your awesome work!

I have one questions related to the training of the signed distance map described in "Shape-Aware Organ Segmentation by Predicting Signed Distance Maps"

As described in the paper, after apply the smooth approximation to the Heaviside function, the boundary of the SDM should convert from 0 to 0.5. (inside the boundary should be 1, and outside value should be 0.). I just not sure how such conversion could overlap witht the binary ground truth?

Thank you for your advise.

Qi

**Comment by tommy-qichang** [comment]
Another question is the definition of the smooth approximation to the Heaviside function in the paper 
![image](https://user-images.githubusercontent.com/19438484/106375935-9999c800-635e-11eb-9bb1-87e4efd14ad0.png)
Seems different from your implementation:

`gt_dis_prob = torch.sigmoid(-1500*gt_dis)`

**Comment by JunMa11** [comment]
Hi @tommy-qichang ,

Thanks for your interest.

> I just not sure how such conversion could overlap with the binary ground truth?

You can check it with some simple code. e.g., 
- compute the sdf of the GT (\phi_GT)
- compute H(\phi_GT)
- compute the DSC between H(\phi_GT) and GT

> Seems different from your implementation:

there is a typo in Eq. (3). 
It should be $f(x) = 1/(1+exp(1500x))$.

Best,
Jun

**Comment by tommy-qichang** [comment]
Hi Jun,
Thank you for your clarification.
I saw the code you mentioned to calcuate sdf at: [compute_sdf](https://github.com/JunMa11/SegWithDistMap/blob/e0281f599feebf352d2c0eb9b24a4c4317bf4c87/code/train_LA_AAAISDF.py#L64 )
, and then apply :
`gt_dis_prob = torch.sigmoid(-1500*gt_dis)`

But when I calculate, because all the baundary you set as 0 :
`sdf[boundary==1] = 0`

Then, after apply sigmoid, the gt_dis_prob become 0.5, while the ground truth mask should be 1.
I don't know if I miss something?

Thanks for your patient.

Qi

**Comment by JunMa11** [comment]
Hi @tommy-qichang,

I apologize for the very late reply. Recently, I'm busy with the [FLARE21 Challenge](https://flare.grand-challenge.org/).

Regarding your question, yes, the gt_dis_prob becomes 0.5 on the boundary. This is because the derived probability map ranges [0,1] and 0.5 level-set corresponds to the boundary. 
Of course, one can shift the boundary probability map to 1 but I do not think it will have too much positive impact on the performance.

Please feel free to raise any questions:)

Best,
Jun
