### ISSUE TITLE
A question of train

### ISSUE THREAD

**Issue by WeiliJiang** [JunMa11/SegWithDistMap#14]
Hello,
I am very interested in you work, and try to use this code in my segmentation task. but i have some question of it. I am try use code like train_LA_MultiHead_FGDTM_L1 in my segment work, and epoch_numbers is 10000, but when i use torch.save model to test data, they will get the predict all is 0. and the dist is also. and i try to print the predict_y that unprocess via argmax. and i foud that y[:,0,:,:,:] is all bigger than y[:,1,:,:,:]. it means the net can't distinguish the foreground and background. so, please give me some advice. thanks.

**Comment by JunMa11** [comment]
Hi @WeiliJiang ,

I apologize for the very late reply. Recently, I'm busy with the [FLARE21 Challenge](https://flare.grand-challenge.org/).

Regarding your question, I have not met this problem. I would recommend trying the plain V-Net to check whether such a problem still occurs.
