### ISSUE TITLE
How to use the SDF for mutli-label mask?

### ISSUE THREAD

**Issue by SkyeC77** [JunMa11/SegWithDistMap#15]
I want to regress the signed distance map with a new head, but it's for a binary mask in your paper. I wonder what should I do if I want to use it for a multi-label mask? 
is it possible to get the SDF image for a three-label ground truth? like the BraTS dataset. 
Hope for your reply.

**Comment by JunMa11** [comment]
Hi @SkyeC77 ,

I apologize for the very late reply. Recently, I'm busy with the [FLARE21 Challenge](https://flare.grand-challenge.org/).

Actually, the SDF implementation should support multi-class segmentation.

https://github.com/JunMa11/SegWithDistMap/blob/153dabf3bc5d9e48058e1497857ac6b00c7abab8/code/train_LA_MultiHead_SDF_L1.py#L76
