### ISSUE TITLE
About the data 

### ISSUE THREAD

**Issue by Puzzled-Hui** [JunMa11/SegWithDistMap#16]
Hi, the link you provided of  MICCAI 2018 Atrial Segmentation Challenge is not the h5 format you claimed, may you re-provide a h5 format MICCAI 2018 Atrial Segmentation Challenge Data?

**Comment by JunMa11** [comment]
Hi @Puzzled-Hui ,

Please try this [link](https://share.weiyun.com/IjRZfaUg).

**Comment by Puzzled-Hui** [comment]
> Hi @Puzzled-Hui ,
> 
> Please try this [link](https://share.weiyun.com/IjRZfaUg).

Thanks! :)
