### ISSUE TITLE
The problem of processing own data into H5 data

### ISSUE THREAD

**Issue by minhoooo1** [JunMa11/SegWithDistMap#17]
Hello author！ I am very interested in your work. I think your work is very frontier and challenging. I also want to use the code here to segment my own 3D enhanced CT image (nifti format 3D image). How do you process the data into H5 format? thank you!

**Comment by JunMa11** [comment]
Hi @minhoooo1 ,

Thanks for your kind word.

Hope this function can help you:)
https://github.com/yulequan/UA-MT/blob/88ed29ad794f877122e542a7fa9505a76fa83515/code/dataloaders/la_heart_processing.py#L9

**Comment by minhoooo1** [comment]
In order to understand the data processing process more clearly.Could you please provide the original data not processed into H5 format &nbsp;! Thank you very much !



发自我的iPhone


------------------ Original ------------------
From: Jun ***@***.***&gt;
Date: Wed,May 5,2021 10:16 AM
To: JunMa11/SegWithDistMap ***@***.***&gt;
Cc: minhoooo1 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [JunMa11/SegWithDistMap] The problem of processing own data into H5 data (#17)





 
Hi @minhoooo1 ,
 
Thanks for your kind word.
 
Hope this function can help you:)
 https://github.com/yulequan/UA-MT/blob/88ed29ad794f877122e542a7fa9505a76fa83515/code/dataloaders/la_heart_processing.py#L9

**Comment by minhoooo1** [comment]
看到您知乎上的评论回复，好像原始数据并不允许分享，那么在这里我只想请求一张nrrd格式的图片，不知道方不方便呢。感谢了🙏！





发自我的iPhone


------------------ Original ------------------
From: Jun ***@***.***&gt;
Date: Wed,May 5,2021 10:16 AM
To: JunMa11/SegWithDistMap ***@***.***&gt;
Cc: minhoooo1 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [JunMa11/SegWithDistMap] The problem of processing own data into H5 data (#17)





 
Hi @minhoooo1 ,
 
Thanks for your kind word.
 
Hope this function can help you:)
 https://github.com/yulequan/UA-MT/blob/88ed29ad794f877122e542a7fa9505a76fa83515/code/dataloaders/la_heart_processing.py#L9

**Comment by minhoooo1** [comment]
Hello author, I'm sorry to disturb you again. Today, I seriously studied the data processing. At present, I only have this section of code. I don't understand it very well. Please explain it  Thank you!
https://github.com/yulequan/UA-MT/blob/88ed29ad794f877122e542a7fa9505a76fa83515/code/dataloaders/la_heart_processing.py#L14

**Comment by minhoooo1** [comment]
I'm sorry to disturb you for so long. I've got it Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月16日(星期天) 晚上9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JunMa11/SegWithDistMap] The problem of processing own data into H5 data (#17)





 
Closed #17.
