### ISSUE TITLE
reproduce LA dataset Multi-heads: SDF-L2

### ISSUE THREAD

**Issue by buaapengbo** [JunMa11/SegWithDistMap#18]
Hi JunMa,

Thanks for your great work! and can you give me advice when tuning the model.

I tried the `code/train_LA_MultiHead_SDF_L2.py` with the default settings and no change.

After training is done, use `code/test_LA_MultiHead_SDF.py` to test the model, the results are:
`
root@475e8e50b861:/Documents/SegWithDistMap/code# python test_LA_MultiHead_SDF.py 
init weight from ../model_la/vnet_dp_la_MH_SDFL2/iter_10000.pth
100%| ... | 20/20 [00:54<00:00,  2.74s/it]
average metric is [ 0.84311185  0.73323151 22.54856166  5.7714824 ]
`

There is still gap to the paper presents:
`Multi-heads: SDF-L2 87.0 (3.49) 77.2 (5.49) 16.1 (13.5) 3.97 (3.14)`

Any idea about the settings at the training stage, like lr, batch size, iteration, etc.

Thanks

**Comment by JunMa11** [comment]
Hi @buaapengbo ,

Thanks for your interest.

I asked [Rongfei Lv](https://github.com/lrfdl) for the potential reason. He trained the model with the same settings on TITAN RTX. The potential reason could be using different GPU.

He also provided the training logs:
https://share.weiyun.com/JRANUnwp
Hope it can help you:)

Best,
Jun

**Comment by buaapengbo** [comment]
Thank you for your reply! It helps, will use TITAN RTX to have a try :)
