### ISSUE TITLE
About Loss Divergent

### ISSUE THREAD

**Issue by YangHan-Morningstar** [JunMa11/SegWithDistMap#19]
Hi, thanks for your great work!
When I run train_LA_AAAISDF.py, I use tensor board to see the change of total loss function and found it became divergent after 1.4k. So I use the model in 1k to test and get an unexpected result, Could tell me how to fix it? Thanks a lot!
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/67748964/140925476-3ad9021d-d1a6-4da0-915b-69332caa800e.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/67748964/140925514-e1f9f0fb-4b61-4035-907f-dd7eb160c4e6.png">

**Comment by JunMa11** [comment]
Hi @YangHan-Morningstar ,

Thanks for your interest very much.

However, it is also weird to me. I haven't encountered this problem yet.  I’m sorry that I do not have a good idea for you.

Best,
Jun

**Comment by YangHan-Morningstar** [comment]
After that I continue to train until it's end and found it became converges after some epoch, I do think it's weird. But when I test the final model, I got the test result which was still little worse than the result in paper.
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/67748964/141219896-b2f5a7ee-7a4d-4b48-8553-b11f1446e04c.png">
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/67748964/141220162-0ac9af9a-dda6-4753-97f2-3d4ae2f6e362.png">
