### ISSUE TITLE
Terrific work

### ISSUE THREAD

**Issue by HKervadec** [JunMa11/SegWithDistMap#3]
Not an issue, but don't really know where to post that otherwise.

I think you made an awesome work at comparing all those settings, and I am happy that your paper got accepted at MIDL 2020.

The code that you provide is very useful, especially the implementation of `Karimi, D. and Salcudean, S.E., 2019. Reducing the Hausdorff distance in medical image segmentation with convolutional neural networks. IEEE transactions on medical imaging.`

Best,

Hoel

**Comment by JunMa11** [comment]
Hi Hoel,

I'm so happy that our work is useful to you.

I also really enjoy your boundary loss, very insightful motivation and beautiful mathematics.

Best,
Jun
