### ISSUE TITLE
Missing citation

### ISSUE THREAD

**Issue by Bala93** [JunMa11/SegWithDistMap#4]
Have a look at these papers, they also have done similar work. 

https://ieeexplore.ieee.org/abstract/document/8857339 
https://link.springer.com/chapter/10.1007/978-3-030-32692-0_34

Papers are available in arxiv (https://arxiv.org/abs/1902.04099, https://arxiv.org/abs/1908.05311).

Code is available at https://github.com/Bala93/Multi-task-deep-network

**Comment by JunMa11** [comment]
Hi @Bala93 

Thanks for sharing the great work.
I have added it to the main refs.

Best,
Jun
