### ISSUE TITLE
heart MRI data MICCAI 2018 Atrial Segmentation Challenge.

### ISSUE THREAD

**Issue by wxr521314** [JunMa11/SegWithDistMap#5]
Hi Jun Ma：
     Thank you for sharing. I can't download heart MRI data MICCAI 2018 Atrial Segmentation Challenge, can you provide it？
I have a rectal data in our lab, and I want to run it with your code. How can I modify my data?

Best wish！

**Comment by JunMa11** [comment]
Hi @wxr521314 ,

Sorry for my late reply.
I'd love to, but unfortunately, the dataset license **does not** allow me to share it. You can send an email to the challenger organizer to get the dataset.

For your own dataset, you should convert it to h5 file before sending it to the network.
Of course, you can write your own dataloader.

Best,
Jun

**Comment by JunMa11** [comment]
Hi @wxr521314 ,

Please try the preprocessed [h5 files](https://share.weiyun.com/IjRZfaUg).
