### ISSUE TITLE
boundary loss based on sdf may be negtive

### ISSUE THREAD

**Issue by yangyuren03** [JunMa11/SegWithDistMap#7]
HI, Thanks for your great work!
I want to know whether the [boundary loss](https://github.com/JunMa11/SegWithDistMap/blob/master/code/train_LA_BD.py) may be negtive value.
Thanks!

**Comment by cuicathy** [comment]
I think it is because the distance map within the boundary has negative values.

**Comment by yangyuren03** [comment]
@cuicathy ,thanks! Do you have a trial with the boundary loss only and does it convergence?

**Comment by cuicathy** [comment]
@yangyuren03 With the boundary loss only, the model converges on my dataset, though it is not as good as using the dice loss only.

**Comment by JunMa11** [comment]
Hi @yangyuren03 ,

Sorry for my late reply.

> I want to know whether the boundary loss may be negative value.

The direct answer is Yes! This is because the sdf takes negative values inside the contour. You can find more details in their paper.
