### ISSUE TITLE
Data Preprocess

### ISSUE THREAD

**Issue by sniperwqza** [JunMa11/SegWithDistMap#8]
Hi, thanks for the great work.

In your paper, you said that "all the cases were **cropped centering at the heart or liver region** for better comparison ... "

May I ask what are the final cropped image sizes in your experiment? When I ran your codes, I found that the size of cropped image is critical to the results of the experiments. But I didn't find the crop size in your paper or codes. I'm confused about it.

If you have any other data preprocessing technology of if I misunderstand anything, please let me know. 

Thank you very much!

**Comment by JunMa11** [comment]
Hi @sniperwqza , Thanks for your interest very much.
The data preprocessing followed lequan's repo.
Here you go:https://github.com/yulequan/UA-MT/blob/master/code/dataloaders/la_heart_processing.py

Best,
Jun

**Comment by sniperwqza** [comment]
I got it! Thanks for your reply! 
Best wishes for you! @JunMa11
